[package]
name = "snemulator"
version = "0.1.0"
edition = "2021"

[package.metadata.packager]
name = "snemulator"
product-name = "Snemulator"
identifier = "io.github.mrbubblezsz.snemulator"
before-packaging-command = "bash scripts/build.sh"

icons = [
    "assets/logo/snemulator-logo.ico",
    "assets/logo/snemulator-logo.icns",
    "assets/logo/icons/32x32.png",
    "assets/logo/icons/128x128.png",
    "assets/logo/icons/128x128@2x.png",
    "assets/logo/icons/256x256.png",
]

[[package.metadata.packager.binaries]]
path = "snemulator"
main = true

[dependencies]
snemcore = { path = "../snemcore" }
paste = "1.0.15"
ringbuf = "0.4.8"
rfd = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
crc32fast = { workspace = true }
egui = { workspace = true }
egui_glow = { workspace = true }
egui_extras = { workspace = true }
glow = { workspace = true }
sdl3 = { workspace = true }
clap = { version = "4.6.1", features = ["derive"] }
serde = { workspace = true }
dirs = "6.0.0"
toml = "1.1.2"
bincode-next = { version = "3.1.1", features = ["serde"] }
serde_json = "1.0.150"
rubato = "3.0.0"
ureq = { version = "3.3.0", features = ["json"] }
image = { workspace = true }
gilrs = "0.11.2"

[features]
debug = []

[build-dependencies]
winresource = "0.1"