pub const NMIPENDING_NOTE: &str = "NMI pending flag is set when the PPU enters its vertical blanking period and the VBlank NMI enable bit is set in the NMITIMEN register ($4200). It becomes clear when the CPU handles the NMI.";
pub const IRQPENDING_NOTE: &str = "IRQ pending flag is set when the current dot and scanline match the condition set in the NMITIMEN register ($4200). It becomes clear when the CPU handles the IRQ, which will only happen when the CPU's IRQ disable bit of the status register is clear.";
pub const STOPPED_NOTE:    &str = "CPU is stopped when DMA or HDMA is in progress.";
pub const DOT_NOTE:        &str = "First visible dot = 22\nLast visible dot = 278";
pub const SCANLINE_NOTE:   &str = "First visible scanline = 1\nLast visible scanline = 261";
pub const C_NOTE: &str = "Bit 0 of the CPU's status register";
pub const Z_NOTE: &str = "Bit 1 of the CPU's status register";
pub const I_NOTE: &str = "Bit 2 of the CPU's status register\nThe CPU will not handle IRQs when this bit is set.";
pub const D_NOTE: &str = "Bit 3 of the CPU's status register";
pub const X_NOTE: &str = "Bit 4 of the CPU's status register";
pub const M_NOTE: &str = "Bit 5 of the CPU's status register";
pub const V_NOTE: &str = "Bit 6 of the CPU's status register";
pub const N_NOTE: &str = "Bit 7 of the CPU's status register";